png("exdata-data-household_power_consumption/plot4.png")
data<-read.table("exdata-data-household_power_consumption/household_power_consumption.txt",sep=";",header=TRUE,colClasses="character")
data_<-data[data$Date=="1/2/2007"|data$Date=="2/2/2007",]
time<-strptime(paste(data_$Date,data_$Time),"%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_TIME","English")
par("mfrow"=c(2,2))
plot(time,data_$Global_active_power,xlab="",ylab="Global Active Power",type="l")
plot(time,data_$Voltage,xlab="datetime",ylab="Voltage",type="l")
plot(time,data_$Sub_metering_1,xlab="",ylab="Energy sub metering",type="n")
points(time,data_$Sub_metering_1,type="l")
points(time,data_$Sub_metering_2,type="l",col="red")
points(time,data_$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,bty="n")
plot(time,data_$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()